name: Prettier Formatter Check

on:
  # Manual trigger
  workflow_dispatch:

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Check formatting with Prettier
        id: prettier_check # Add an ID to use in subsequent steps
        run: |
          if npx prettier --check . ; then
            echo "Formatting is ok"
          else
            echo "Formatting issues found"
            exit 1 #  Ensure workflow fails if formatting issues are present
          fi
      - name: Fix formatting with Prettier (if issues found)
        if: ${{ failure() }} # Only run if the previous step failed
        run: |
          npx prettier --write .
        
      - name: Create a commit with the formatting changes
        if: ${{ failure() }}  # Only run if the previous step failed
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Fix formatting with Prettier" || echo "No changes to commit"
          git push
